#固定模板
server:
  port: 8002
#项目名
spring:
  application:
    name: service-oss
  #环境设置
  profiles:
    active: dev
  #debug: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos注册与发现