server:
  port: 8007
spring:
  #\u670D\u52A1\u540D
  application:
    name: service-order
    #\u5F00\u53D1\u73AF\u5883
  profiles:
    active: dev #\u4F7F\u7528dev\u914D\u7F6E\u4E3A\u5FF5
    #\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/gedu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    type: com.zaxxer.hikari.HikariDataSource #\u4F7F\u7528\u5185\u7F6E\u7684\u6570\u636E\u6E90, \u53F7\u79F0\u6700\u5FEB
    hikari:
      minimum-idle: 5 #\u6700\u5C0F\u95F2\u7F6E\u6570 \u540C min-idle
      maximum-pool-size: 12 #\u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\u9ED8\u8BA410, \u540Cmax-active
      idle-timeout: 500000 #\u7A7A\u95F2\u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4, \u7F3A\u7701600000
      max-lifetime: 54000 #\u4E00\u4E2A\u8FDE\u63A5\u7684\u751F\u547D\u65F6\u957F, \u8D85\u65F6\u800C\u4E14\u6CA1\u6709\u88AB\u4F7F\u7528\u5219\u88AB\u91CA\u653E, \u7F3A\u7701600000
      auto-commit: true #\u63A7\u5236\u4ECE\u8BE5\u8FDE\u63A5\u6C60\u83B7\u53D6\u7684\u8FDE\u63A5\u662F\u5426\u81EA\u52A8\u63D0\u4EA4
      connection-test-query: SELECT 1 #\u7528\u4E8E\u6821\u9A8C\u8FDE\u63A5\u662F\u5426\u6709\u6548, druid\u540Cvalidation-query
      pool-name: HikariPool #\u51FA\u73B0\u5728\u65E5\u5FD7\u4E2D\u7684\u8FDE\u63A5\u6C60\u540D\u5B57
    #jackson,\u65F6\u95F4\u8FD4\u56DE\u7684\u5168\u5C40\u683C\u5F0F, \u4E0D\u4F1A\u5BF9LocalDateTime\u751F\u6548
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #mybatis-plus
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u5F00\u542Flog\u65E5\u5FD7
  global-config:
    db-config:
      logic-delete-field: deleted #\u903B\u8F91\u5220\u9664
      logic-delete-value: 1 #\u5DF2\u5220\u9664\u7684\u503C, \u9ED8\u8BA41
      logic-not-delete-value: 0 #\u672A\u5220\u9664\u7684, \u9ED8\u8BA40
  #\u914D\u7F6Exml\u626B\u63CF, classpath\u5BF9\u5E94\u7684\u5F53\u524D\u6A21\u5757
  mapper-locations:
    - classpath:com/chz/eduservice/mapper/xml/*.xml
#\u7531logback\u63A5\u7BA1
#\u63A7\u5236\u53F0\u65E5\u5FD7\u7EA7\u522B
#logging:
#  level:
#    root: info
#  file:
#    path: log/edu.log
feign: #\u5F00\u542F\u7194\u65AD\u673A\u5236
  hystrix:
    enabled: true
    #\u8BBE\u7F6Ehystrix\u8D85\u65F6\u65F6\u95F4, \u9ED8\u8BA41000ms