server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #和zull相同, 同样需要注入到服务注册中心
    gateway:
      enabled: true #开启网关, 缺省为true
      routes:
        - id: service-edu #服务的id, 可以是任意值
          uri: lb://service-edu #请求转发的uri
          predicates:
            - Path=/eduservice/** #只有断言为true才会转发到目标地址, 一般用于匹配路径
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/eduorder/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/educms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduoss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/edusms/**
        - id: service-statics
          uri: lb://service-statics
          predicates:
            - Path=/statics/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/api/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/eduvod/**
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/admin/acl/**